const flags = [
    { name: "Afghanistan", code: "af", difficulty: 1 },
    { name: "Albania", code: "al", difficulty: 1 },
    { name: "Algeria", code: "dz", difficulty: 1 },
    { name: "Andorra", code: "ad", difficulty: 1 },
    { name: "Angola", code: "ao", difficulty: 1 },
    { name: "Antigua and Barbuda", code: "ag", difficulty: 1 },
    { name: "Argentina", code: "ar", difficulty: 1 },
    { name: "Armenia", code: "am", difficulty: 1 },
    { name: "Australia", code: "au", difficulty: 1 },
    { name: "Austria", code: "at", difficulty: 1 },
    { name: "Azerbaijan", code: "az", difficulty: 1 },
    { name: "Bahamas", code: "bs", difficulty: 1 },
    { name: "Bahrain", code: "bh", difficulty: 1 },
    { name: "Bangladesh", code: "bd", difficulty: 1 },
    { name: "Barbados", code: "bb", difficulty: 1 },
    { name: "Belarus", code: "by", difficulty: 1 },
    { name: "Belgium", code: "be", difficulty: 1 },
    { name: "Belize", code: "bz", difficulty: 1 },
    { name: "Benin", code: "bj", difficulty: 1 },
    { name: "Bhutan", code: "bt", difficulty: 1 },
    { name: "Bolivia", code: "bo", difficulty: 1 },
    { name: "Bosnia and Herzegovina", code: "ba", difficulty: 1 },
    { name: "Botswana", code: "bw", difficulty: 1 },
    { name: "Brazil", code: "br", difficulty: 1 },
    { name: "Brunei", code: "bn", difficulty: 1 },
    { name: "Bulgaria", code: "bg", difficulty: 1 },
    { name: "Burkina Faso", code: "bf", difficulty: 1 },
    { name: "Burundi", code: "bi", difficulty: 1 },
    { name: "Cambodia", code: "kh", difficulty: 1 },
    { name: "Cameroon", code: "cm", difficulty: 1 },
    { name: "Canada", code: "ca", difficulty: 1 },
    { name: "Cape Verde", code: "cv", difficulty: 1 },
    { name: "Central African Republic", code: "cf", difficulty: 1 },
    { name: "Chad", code: "td", difficulty: 1 },
    { name: "Chile", code: "cl", difficulty: 1 },
    { name: "China", code: "cn", difficulty: 1 },
    { name: "Colombia", code: "co", difficulty: 1 },
    { name: "Comoros", code: "km", difficulty: 1 },
    { name: "Congo", code: "cg", difficulty: 1 },
    { name: "Democratic Republic of the Congo", code: "cd", difficulty: 1 },
    { name: "Costa Rica", code: "cr", difficulty: 1 },
    { name: "Croatia", code: "hr", difficulty: 1 },
    { name: "Cuba", code: "cu", difficulty: 1 },
    { name: "Cyprus", code: "cy", difficulty: 1 },
    { name: "Czech Republic", code: "cz", difficulty: 1 },
    { name: "Denmark", code: "dk", difficulty: 1 },
    { name: "Djibouti", code: "dj", difficulty: 1 },
    { name: "Dominica", code: "dm", difficulty: 1 },
    { name: "Dominican Republic", code: "do", difficulty: 1 },
    { name: "Ecuador", code: "ec", difficulty: 1 },
    { name: "Egypt", code: "eg", difficulty: 1 },
    { name: "El Salvador", code: "sv", difficulty: 1 },
    { name: "Equatorial Guinea", code: "gq", difficulty: 1 },
    { name: "Eritrea", code: "er", difficulty: 1 },
    { name: "Estonia", code: "ee", difficulty: 1 },
    { name: "Eswatini", code: "sz", difficulty: 1 },
    { name: "Ethiopia", code: "et", difficulty: 1 },
    { name: "Fiji", code: "fj", difficulty: 1 },
    { name: "Finland", code: "fi", difficulty: 1 },
    { name: "France", code: "fr", difficulty: 1 },
    { name: "Gabon", code: "ga", difficulty: 1 },
    { name: "Gambia", code: "gm", difficulty: 1 },
    { name: "Georgia", code: "ge", difficulty: 1 },
    { name: "Germany", code: "de", difficulty: 1 },
    { name: "Ghana", code: "gh", difficulty: 1 },
    { name: "Greece", code: "gr", difficulty: 1 },
    { name: "Grenada", code: "gd", difficulty: 1 },
    { name: "Guatemala", code: "gt", difficulty: 1 },
    { name: "Guinea", code: "gn", difficulty: 1 },
    { name: "Guinea-Bissau", code: "gw", difficulty: 1 },
    { name: "Guyana", code: "gy", difficulty: 1 },
    { name: "Haiti", code: "ht", difficulty: 1 },
    { name: "Honduras", code: "hn", difficulty: 1 },
    { name: "Hungary", code: "hu", difficulty: 1 },
    { name: "Iceland", code: "is", difficulty: 1 },
    { name: "India", code: "in", difficulty: 1 },
    { name: "Indonesia", code: "id", difficulty: 1 },
    { name: "Iran", code: "ir", difficulty: 1 },
    { name: "Iraq", code: "iq", difficulty: 1 },
    { name: "Ireland", code: "ie", difficulty: 1 },
    { name: "Israel", code: "il", difficulty: 1 },
    { name: "Italy", code: "it", difficulty: 1 },
    { name: "Ivory Coast", code: "ci", difficulty: 1 },
    { name: "Jamaica", code: "jm", difficulty: 1 },
    { name: "Japan", code: "jp", difficulty: 1 },
    { name: "Jordan", code: "jo", difficulty: 1 },
    { name: "Kazakhstan", code: "kz", difficulty: 1 },
    { name: "Kenya", code: "ke", difficulty: 1 },
    { name: "Kiribati", code: "ki", difficulty: 1 },
    { name: "Kuwait", code: "kw", difficulty: 1 },
    { name: "Kyrgyzstan", code: "kg", difficulty: 1 },
    { name: "Laos", code: "la", difficulty: 1 },
    { name: "Latvia", code: "lv", difficulty: 1 },
    { name: "Lebanon", code: "lb", difficulty: 1 },
    { name: "Lesotho", code: "ls", difficulty: 1 },
    { name: "Liberia", code: "lr", difficulty: 1 },
    { name: "Libya", code: "ly", difficulty: 1 },
    { name: "Liechtenstein", code: "li", difficulty: 1 },
    { name: "Lithuania", code: "lt", difficulty: 1 },
    { name: "Luxembourg", code: "lu", difficulty: 1 },
    { name: "Madagascar", code: "mg", difficulty: 1 },
    { name: "Malawi", code: "mw", difficulty: 1 },
    { name: "Malaysia", code: "my", difficulty: 1 },
    { name: "Maldives", code: "mv", difficulty: 1 },
    { name: "Mali", code: "ml", difficulty: 1 },
    { name: "Malta", code: "mt", difficulty: 1 },
    { name: "Marshall Islands", code: "mh", difficulty: 1 },
    { name: "Mauritania", code: "mr", difficulty: 1 },
    { name: "Mauritius", code: "mu", difficulty: 1 },
    { name: "Mexico", code: "mx", difficulty: 1 },
    { name: "Micronesia", code: "fm", difficulty: 1 },
    { name: "Moldova", code: "md", difficulty: 1 },
    { name: "Monaco", code: "mc", difficulty: 1 },
    { name: "Mongolia", code: "mn", difficulty: 1 },
    { name: "Montenegro", code: "me", difficulty: 1 },
    { name: "Morocco", code: "ma", difficulty: 1 },
    { name: "Mozambique", code: "mz", difficulty: 1 },
    { name: "Myanmar", code: "mm", difficulty: 1 },
    { name: "Namibia", code: "na", difficulty: 1 },
    { name: "Nauru", code: "nr", difficulty: 1 },
    { name: "Nepal", code: "np", difficulty: 1 },
    { name: "Netherlands", code: "nl", difficulty: 1 },
    { name: "New Zealand", code: "nz", difficulty: 1 },
    { name: "Nicaragua", code: "ni", difficulty: 1 },
    { name: "Niger", code: "ne", difficulty: 1 },
    { name: "Nigeria", code: "ng", difficulty: 1 },
    { name: "North Korea", code: "kp", difficulty: 1 },
    { name: "North Macedonia", code: "mk", difficulty: 1 },
    { name: "Norway", code: "no", difficulty: 1 },
    { name: "Oman", code: "om", difficulty: 1 },
    { name: "Pakistan", code: "pk", difficulty: 1 },
    { name: "Palau", code: "pw", difficulty: 1 },
    { name: "Palestine", code: "ps", difficulty: 1 },
    { name: "Panama", code: "pa", difficulty: 1 },
    { name: "Papua New Guinea", code: "pg", difficulty: 1 },
    { name: "Paraguay", code: "py", difficulty: 1 },
    { name: "Peru", code: "pe", difficulty: 1 },
    { name: "Philippines", code: "ph", difficulty: 1 },
    { name: "Poland", code: "pl", difficulty: 1 },
    { name: "Portugal", code: "pt", difficulty: 1 },
    { name: "Qatar", code: "qa", difficulty: 1 },
    { name: "Romania", code: "ro", difficulty: 1 },
    { name: "Russia", code: "ru", difficulty: 1 },
    { name: "Rwanda", code: "rw", difficulty: 1 },
    { name: "Saint Kitts and Nevis", code: "kn", difficulty: 1 },
    { name: "Saint Lucia", code: "lc", difficulty: 1 },
    { name: "Saint Vincent and the Grenadines", code: "vc", difficulty: 1 },
    { name: "Samoa", code: "ws", difficulty: 1 },
    { name: "San Marino", code: "sm", difficulty: 1 },
    { name: "Sao Tome and Principe", code: "st", difficulty: 1 },
    { name: "Saudi Arabia", code: "sa", difficulty: 1 },
    { name: "Senegal", code: "sn", difficulty: 1 },
    { name: "Serbia", code: "rs", difficulty: 1 },
    { name: "Seychelles", code: "sc", difficulty: 1 },
    { name: "Sierra Leone", code: "sl", difficulty: 1 },
    { name: "Singapore", code: "sg", difficulty: 1 },
    { name: "Slovakia", code: "sk", difficulty: 1 },
    { name: "Slovenia", code: "si", difficulty: 1 },
    { name: "Solomon Islands", code: "sb", difficulty: 1 },
    { name: "Somalia", code: "so", difficulty: 1 },
    { name: "South Africa", code: "za", difficulty: 1 },
    { name: "South Korea", code: "kr", difficulty: 1 },
    { name: "South Sudan", code: "ss", difficulty: 1 },
    { name: "Spain", code: "es", difficulty: 1 },
    { name: "Sri Lanka", code: "lk", difficulty: 1 },
    { name: "Sudan", code: "sd", difficulty: 1 },
    { name: "Suriname", code: "sr", difficulty: 1 },
    { name: "Sweden", code: "se", difficulty: 1 },
    { name: "Switzerland", code: "ch", difficulty: 1 },
    { name: "Syria", code: "sy", difficulty: 1 },
    { name: "Taiwan", code: "tw", difficulty: 1 },
    { name: "Tajikistan", code: "tj", difficulty: 1 },
    { name: "Tanzania", code: "tz", difficulty: 1 },
    { name: "Thailand", code: "th", difficulty: 1 },
    { name: "Timor-Leste", code: "tl", difficulty: 1 },
    { name: "Togo", code: "tg", difficulty: 1 },
    { name: "Tonga", code: "to", difficulty: 1 },
    { name: "Trinidad and Tobago", code: "tt", difficulty: 1 },
    { name: "Tunisia", code: "tn", difficulty: 1 },
    { name: "Turkey", code: "tr", difficulty: 1 },
    { name: "Turkmenistan", code: "tm", difficulty: 1 },
    { name: "Tuvalu", code: "tv", difficulty: 1 },
    { name: "Uganda", code: "ug", difficulty: 1 },
    { name: "Ukraine", code: "ua", difficulty: 1 },
    { name: "United Arab Emirates", code: "ae", difficulty: 1 },
    { name: "United Kingdom", code: "gb", difficulty: 1 },
    { name: "United States", code: "us", difficulty: 1 },
    { name: "Uruguay", code: "uy", difficulty: 1 },
    { name: "Uzbekistan", code: "uz", difficulty: 1 },
    { name: "Vanuatu", code: "vu", difficulty: 1 },
    { name: "Vatican City", code: "va", difficulty: 1 },
    { name: "Venezuela", code: "ve", difficulty: 1 },
    { name: "Vietnam", code: "vn", difficulty: 1 },
    { name: "Yemen", code: "ye", difficulty: 1 },
    { name: "Zambia", code: "zm", difficulty: 1 },
    { name: "Zimbabwe", code: "zw", difficulty: 1 },
    { name: "Antarctica", code: "aq", difficulty: 1 },
    { name: "Kosovo", code: "xk", difficulty: 1 },
]

function getFlag(code) {
    return `https://flagcdn.com/w320/${code}.png`;
}

const datalist = document.getElementById("flag-autocompletes");
flags.forEach(flag => {
    const option = document.createElement("option");
    option.value = flag.name;
    datalist.appendChild(option);
});